#!/usr/bin/env bash
# Stage 16: installs automation/*.sh into ~/scripts/automation, writes a
# root-only config file the automation scripts read at runtime, and
# installs/enables the systemd timers that drive daily backups, the
# 15-minute health check, and weekly update/cleanup maintenance.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/lib/common.sh"
require_root
require_env ADMIN_USER

step "Install rclone (optional offsite backup sync target, e.g. DO Spaces)"
apt_install rclone

ADMIN_HOME="/home/${ADMIN_USER}"

step "Install automation scripts to ${ADMIN_HOME}/scripts/automation"
install -d -o "$ADMIN_USER" -g "$ADMIN_USER" "${ADMIN_HOME}/scripts/automation"
install -m 750 -o root -g root "${ROOT_DIR}"/automation/*.sh "${ADMIN_HOME}/scripts/automation/"

step "Write /etc/echo-protocol/automation.env (root-only; automation scripts source it)"
install -d -m 750 /etc/echo-protocol
{
  echo "# Generated by scripts/16-automation-cron.sh from .env — do not edit .env after"
  echo "# provisioning without re-running this stage, or edit this file directly."
  echo "ADMIN_USER=${ADMIN_USER}"
  echo "BACKUP_ROOT=${BACKUP_ROOT:-/home/${ADMIN_USER}/backups}"
  echo "BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-14}"
  echo "BACKUP_OFFSITE_RCLONE_REMOTE=${BACKUP_OFFSITE_RCLONE_REMOTE:-}"
  echo "REDIS_PASSWORD=${REDIS_PASSWORD:-}"
  echo "HEALTH_CHECK_WEBHOOK_URL=${HEALTH_CHECK_WEBHOOK_URL:-}"
} > /etc/echo-protocol/automation.env
chmod 600 /etc/echo-protocol/automation.env
chown root:root /etc/echo-protocol/automation.env

step "Install systemd units (backup, health-check, weekly maintenance)"
for unit in backup.service backup.timer health-check.service health-check.timer maintenance.service maintenance.timer; do
  sed "s/__ADMIN_USER__/${ADMIN_USER}/g" "${ROOT_DIR}/systemd/${unit}" > "/etc/systemd/system/${unit}"
done

systemctl daemon-reload
systemctl enable --now backup.timer
systemctl enable --now health-check.timer
systemctl enable --now maintenance.timer

step "Timers installed"
systemctl list-timers 'backup.timer' 'health-check.timer' 'maintenance.timer' --no-pager | tee -a "$LOG_FILE"

mark_done "16-automation-cron"
log "Stage 16 complete. Run a manual backup now with: sudo ${ADMIN_HOME}/scripts/automation/backup-run.sh"
